### ISSUE TITLE
err:  ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/download". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#134]
https://github.com/SalamLang/Salam-Website/actions/runs/10774816861/job/29877800187

```
err:  ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/download". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
err:     at o (***.next/server/chunks/150.js:1:11362)
err:     at c (***.next/server/chunks/150.js:1:22359)
err:     at j (***.next/server/app/(WithoutFooter)/download/page.js:1:129[69](https://github.com/SalamLang/Salam-Website/actions/runs/10774816861/job/29877800187#step:4:70))
err:     at nj (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
err:     at nM (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:475[71](https://github.com/SalamLang/Salam-Website/actions/runs/10774816861/job/29877800187#step:4:72))
err:     at nM (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
err:     at nN (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
err:     at nB (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
err:     at nM (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:58560)
err:     at nN (***node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
err: Error occurred prerendering page "/download". Read more: https://nextjs.org/docs/messages/prerender-error
out:  ✓ Generating static pages (7/7)
err: > Export encountered errors on following paths:
err: 	/(WithoutFooter)/download/page: /download
```

**Comment by BaseMax** [comment]
این رو بررسی کردید؟ اگه حل شد ایشو رو ببندید

**Comment by BaseMax** [comment]
Max Base, [9/10/2024 2:47 PM]
اگه حل شده ببندید

Max Base, [9/10/2024 2:47 PM]
احتمالا حل شده که سایت بالاست. بیلد که گرفتید اگه خطا و هشدار نمیده اوکیه
