### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#205]
```
190-9f8a013d4ba4a8fa.js:1 ChunkLoadError
    at Object.j (webpack-cd28abf5c05456ef.js:1:3106)
    at webpack-cd28abf5c05456ef.js:1:1400
    at Array.reduce (<anonymous>)
    at Function.e (webpack-cd28abf5c05456ef.js:1:1366)
    at 190-9f8a013d4ba4a8fa.js:2:18831
    at 190-9f8a013d4ba4a8fa.js:2:19033
    at t (190-9f8a013d4ba4a8fa.js:2:19236)
(anonymous) @ 190-9f8a013d4ba4a8fa.js:1
fd9d1056-beab91476679ab98.js:1 Uncaught Error: Minified React error #423; visit https://react.dev/errors/423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at iZ (fd9d1056-beab91476679ab98.js:1:118349)
    at ia (fd9d1056-beab91476679ab98.js:1:95162)
    at fd9d1056-beab91476679ab98.js:1:94984
    at il (fd9d1056-beab91476679ab98.js:1:94991)
    at oJ (fd9d1056-beab91476679ab98.js:1:92347)
    at oZ (fd9d1056-beab91476679ab98.js:1:91766)
    at MessagePort.M (190-9f8a013d4ba4a8fa.js:1:83875)
```

**Comment by ali-josheghani** [comment]
فیکس کردیم ظاهرا و موقع بیلد گرفتن اروری نمیگیریم
