### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#207]
```
root@maxbasecode:/var/www/html/salamlang.ir# bun run build
$ next build
  ▲ Next.js 14.2.13

   Creating an optimized production build ...
   Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
 ✓ (pwa) Compiling for server...
 ✓ (pwa) Compiling for server...
 ✓ (pwa) Compiling for client (static)...
 ○ (pwa) Service worker: /var/www/html/salamlang.ir/public/sw.js
 ○ (pwa)   URL: /sw.js
 ○ (pwa)   Scope: /
 ✓ Compiled successfully
   Linting and checking validity of types  . ⨯ ESLint: Invalid Options: - Unknown options: useEslintrc, extensions - 'extensions' has been removed.
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (0/9)  [=   ]ReferenceError: window is not defined
    at /var/www/html/salamlang.ir/.next/server/chunks/928.js:1:30050
    at nt (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:38746)
    at Object.useState (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:40703)
    at t.useState (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:110091)
    at l (/var/www/html/salamlang.ir/.next/server/chunks/928.js:1:30028)
    at s (/var/www/html/salamlang.ir/.next/server/chunks/928.js:1:32713)
    at nj (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
    at nM (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
    at nN (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nM (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61156)
ReferenceError: window is not defined
    at /var/www/html/salamlang.ir/.next/server/chunks/928.js:1:30050
    at nt (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:38746)
    at Object.useState (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:40703)
    at t.useState (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:110091)
    at l (/var/www/html/salamlang.ir/.next/server/chunks/928.js:1:30028)
    at s (/var/www/html/salamlang.ir/.next/server/chunks/928.js:1:32713)
    at nj (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
    at nM (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
    at nN (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nM (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61156)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4553:19)
    at successSteps (node:internal/deps/undici/undici:4527:27)
    at fullyReadBody (node:internal/deps/undici/undici:1307:9)
    at async specConsumeBody (node:internal/deps/undici/undici:4536:7)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4553:19)
    at successSteps (node:internal/deps/undici/undici:4527:27)
    at fullyReadBody (node:internal/deps/undici/undici:1307:9)
    at async specConsumeBody (node:internal/deps/undici/undici:4536:7)
ReferenceError: window is not defined
    at /var/www/html/salamlang.ir/.next/server/chunks/928.js:1:30050
    at nt (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:38746)
    at Object.useState (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:40703)
    at t.useState (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:110091)
    at l (/var/www/html/salamlang.ir/.next/server/chunks/928.js:1:30028)
    at s (/var/www/html/salamlang.ir/.next/server/chunks/928.js:1:32713)
    at nj (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
    at nM (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
    at nN (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nM (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61156)
ReferenceError: window is not defined
    at /var/www/html/salamlang.ir/.next/server/chunks/928.js:1:30050
    at nt (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:38746)
    at Object.useState (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:40703)
    at t.useState (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:110091)
    at l (/var/www/html/salamlang.ir/.next/server/chunks/928.js:1:30028)
    at u (/var/www/html/salamlang.ir/.next/server/app/(main)/(WithoutFooter)/playground/page.js:1:92454)
    at nj (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
    at nM (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
    at nM (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
    at nN (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4553:19)
    at successSteps (node:internal/deps/undici/undici:4527:27)
    at fullyReadBody (node:internal/deps/undici/undici:1307:9)
    at async specConsumeBody (node:internal/deps/undici/undici:4536:7)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4553:19)
    at successSteps (node:internal/deps/undici/undici:4527:27)
    at fullyReadBody (node:internal/deps/undici/undici:1307:9)
    at async specConsumeBody (node:internal/deps/undici/undici:4536:7)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4553:19)
    at successSteps (node:internal/deps/undici/undici:4527:27)
    at fullyReadBody (node:internal/deps/undici/undici:1307:9)
    at async specConsumeBody (node:internal/deps/undici/undici:4536:7)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4553:19)
    at successSteps (node:internal/deps/undici/undici:4527:27)
    at fullyReadBody (node:internal/deps/undici/undici:1307:9)
    at async specConsumeBody (node:internal/deps/undici/undici:4536:7)
   Generating static pages (5/9)  [==  ]SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4553:19)
    at successSteps (node:internal/deps/undici/undici:4527:27)
    at fullyReadBody (node:internal/deps/undici/undici:1307:9)
    at async specConsumeBody (node:internal/deps/undici/undici:4536:7)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4553:19)
    at successSteps (node:internal/deps/undici/undici:4527:27)
    at fullyReadBody (node:internal/deps/undici/undici:1307:9)
    at async specConsumeBody (node:internal/deps/undici/undici:4536:7)
ReferenceError: window is not defined
    at /var/www/html/salamlang.ir/.next/server/chunks/928.js:1:30050
    at nt (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:38746)
    at Object.useState (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:40703)
    at t.useState (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:110091)
    at l (/var/www/html/salamlang.ir/.next/server/chunks/928.js:1:30028)
    at s (/var/www/html/salamlang.ir/.next/server/chunks/928.js:1:32713)
    at nj (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
    at nM (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
    at nN (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nM (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61156)
ReferenceError: window is not defined
    at /var/www/html/salamlang.ir/.next/server/chunks/928.js:1:30050
    at nt (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:38746)
    at Object.useState (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:40703)
    at t.useState (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:110091)
    at l (/var/www/html/salamlang.ir/.next/server/chunks/928.js:1:30028)
    at s (/var/www/html/salamlang.ir/.next/server/chunks/928.js:1:32713)
    at nj (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
    at nM (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
    at nN (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nM (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61156)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4553:19)
    at successSteps (node:internal/deps/undici/undici:4527:27)
    at fullyReadBody (node:internal/deps/undici/undici:1307:9)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async specConsumeBody (node:internal/deps/undici/undici:4536:7)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4553:19)
    at successSteps (node:internal/deps/undici/undici:4527:27)
    at fullyReadBody (node:internal/deps/undici/undici:1307:9)
    at async specConsumeBody (node:internal/deps/undici/undici:4536:7)
ReferenceError: window is not defined
    at /var/www/html/salamlang.ir/.next/server/chunks/928.js:1:30050
    at nt (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:38746)
    at Object.useState (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:40703)
    at t.useState (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:110091)
    at l (/var/www/html/salamlang.ir/.next/server/chunks/928.js:1:30028)
    at s (/var/www/html/salamlang.ir/.next/server/chunks/928.js:1:32713)
    at nj (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
    at nM (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
    at nN (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nM (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61156)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4553:19)
    at successSteps (node:internal/deps/undici/undici:4527:27)
    at fullyReadBody (node:internal/deps/undici/undici:1307:9)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async specConsumeBody (node:internal/deps/undici/undici:4536:7)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4553:19)
    at successSteps (node:internal/deps/undici/undici:4527:27)
    at fullyReadBody (node:internal/deps/undici/undici:1307:9)
    at async specConsumeBody (node:internal/deps/undici/undici:4536:7)
ReferenceError: window is not defined
    at /var/www/html/salamlang.ir/.next/server/chunks/928.js:1:30050
    at nt (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:38746)
    at Object.useState (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:40703)
    at t.useState (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:110091)
    at l (/var/www/html/salamlang.ir/.next/server/chunks/928.js:1:30028)
    at s (/var/www/html/salamlang.ir/.next/server/chunks/928.js:1:32713)
    at nj (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
    at nM (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
    at nN (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nM (/var/www/html/salamlang.ir/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61156)
 ✓ Generating static pages (9/9)
 ✓ Collecting build traces
 ✓ Finalizing page optimization

Route (app)                              Size     First Load JS
┌ ○ /                                    100 kB          317 kB
├ ○ /_not-found                          137 B           110 kB
├ ○ /download                            7.1 kB          197 kB
├ ○ /education                           6.42 kB         201 kB
├ ○ /learn                               5.47 kB         116 kB
├ ○ /playground                          23.9 kB         218 kB
└ ○ /supporter                           1.49 kB         118 kB
+ First Load JS shared by all            110 kB
  ├ chunks/145-c1370fe5c7a04e59.js       54.5 kB
  ├ chunks/fd9d1056-5b625bd089dbc90c.js  53.7 kB
  └ other shared chunks (total)          2.04 kB


○  (Static)  prerendered as static content
```

**Comment by ali-josheghani** [comment]
فیکس شده
