### ISSUE TITLE
playground: 145-c1370fe5c7a04e59.js:1 ReferenceError: React is not defined

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#209]
https://salamlang.ir/playground

```
page-cd2b29c3a07a4f85.js:1 r
page-cd2b29c3a07a4f85.js:1 r
page-cd2b29c3a07a4f85.js:1 r
page-cd2b29c3a07a4f85.js:1 r
page-cd2b29c3a07a4f85.js:1 r
page-cd2b29c3a07a4f85.js:1 r
page-cd2b29c3a07a4f85.js:1 r
page-001ce294ac87856e.js:1 User pressed key: undefined
page-001ce294ac87856e.js:1 User clicked on the screen
145-c1370fe5c7a04e59.js:1 ReferenceError: React is not defined
    at ez (page-001ce294ac87856e.js:1:52618)
    at rE (fd9d1056-5b625bd089dbc90c.js:1:40341)
    at iZ (fd9d1056-5b625bd089dbc90c.js:1:117026)
    at ia (fd9d1056-5b625bd089dbc90c.js:1:95162)
    at fd9d1056-5b625bd089dbc90c.js:1:94984
    at il (fd9d1056-5b625bd089dbc90c.js:1:94991)
    at nb (fd9d1056-5b625bd089dbc90c.js:1:26772)
    at nw (fd9d1056-5b625bd089dbc90c.js:1:27571)
    at fd9d1056-5b625bd089dbc90c.js:1:28605
window.console.error @ 145-c1370fe5c7a04e59.js:1
```

**Comment by ali-josheghani** [comment]
fixed
