### ISSUE TITLE
از صفحه روی سلام توی هدر زدم کرش کرد.  Failed to set an indexed property [0] on 'CSSStyleDeclaration': Indexed property setter is not supported.

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#254]
از صفحه روی سلام توی هدر زدم کرش کرد.  Failed to set an indexed property [0] on 'CSSStyleDeclaration': Indexed property setter is not supported.

```
TypeError: Failed to set an indexed property [0] on 'CSSStyleDeclaration': Indexed property setter is not supported.
    at tc (fd9d1056-beab91476679ab98.js:1:13873)
    at tf (fd9d1056-beab91476679ab98.js:1:14238)
    at sY (fd9d1056-beab91476679ab98.js:1:147122)
    at sG (fd9d1056-beab91476679ab98.js:1:153345)
    at fd9d1056-beab91476679ab98.js:1:100459
    at iu (fd9d1056-beab91476679ab98.js:1:103867)
    at ia (fd9d1056-beab91476679ab98.js:1:95223)
    at fd9d1056-beab91476679ab98.js:1:94984
    at il (fd9d1056-beab91476679ab98.js:1:94991)
    at oJ (fd9d1056-beab91476679ab98.js:1:92347)
window.console.error @ 190-877b6a12217b171a.js:1
```

**Comment by ali-josheghani** [comment]
فیکس شده ظاهرا بخاطر اینکه برای استایل دادن به المنت بجای 

```javascript
       style={{ property: value }}
``` 

در jsx اینطوری داده شده :

```javascript
       style="property: value"
```
