### ISSUE TITLE
bun run build - error: script "build" exited with code 1

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Website#288]
```
root@maxbasecode:/var/www/html/salamlang.ir# bun run build
$ next build
   ▲ Next.js 15.0.4
   - Experiments (use with caution):
     · forceSwcTransforms

   Creating an optimized production build ...
 ✓ Compiled successfully

./src/components/molecules/ProblemToDownloadModal.jsx
25:6  Warning: React Hook useCallback has a missing dependency: 'allowScroll'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./src/hooks/useLocalStorage.jsx
44:6  Warning: React Hook useEffect has a missing dependency: 'readValue'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/app/building-your-application/configuring/eslint#disabling-rules
 ✓ Linting and checking validity of types
unhandledRejection TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')
    at Object.<anonymous> (/var/www/html/salamlang.ir/node_modules/react-dom/cjs/react-dom-server-legacy.browser.production.min.js:56:421)
    at mod.require (/var/www/html/salamlang.ir/node_modules/next/dist/server/require-hook.js:65:28)
    at Object.<anonymous> (/var/www/html/salamlang.ir/node_modules/react-dom/server.browser.js:5:7) {
  type: 'TypeError'
}
error: script "build" exited with code 1
```

**Comment by BaseMax** [comment]
bun update
bun upgrade

زده شده

**Comment by BaseMax** [comment]
```

0|salamlang-website  | > next-app@0.1.0 start
0|salamlang-website  | > next start -p 3001
0|salamlang-website  |    ▲ Next.js 15.0.4
0|salamlang-website  |    - Local:        http://localhost:3001
0|salamlang-website  |  ✓ Starting...
0|salamlang-website  | Error: Could not find a production build in the '.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
0|salamlang-website  |     at setupFsCheck (/var/www/html/salamlang.ir/node_modules/next/dist/server/lib/router-utils/filesystem.js:148:19)
0|salamlang-website  |     at async initialize (/var/www/html/salamlang.ir/node_modules/next/dist/server/lib/router-server.js:65:23)
0|salamlang-website  |     at async Server.<anonymous> (/var/www/html/salamlang.ir/node_modules/next/dist/server/lib/start-server.js:266:36)
PM2                  | App [salamlang-website:0] exited with code [1] via signal [SIGINT]
PM2                  | App [salamlang-website:0] starting in -fork mode-
PM2                  | App [salamlang-website:0] online
^C
root@maxbasecode:/var/www/html/salamlang.ir# ^C
root@maxbasecode:/var/www/html/salamlang.ir# bun run build
$ next build
   ▲ Next.js 15.0.4
   - Experiments (use with caution):
     · forceSwcTransforms

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
unhandledRejection TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')
    at Object.<anonymous> (/var/www/html/salamlang.ir/node_modules/react-dom/cjs/react-dom-server-legacy.browser.production.min.js:56:421)
    at mod.require (/var/www/html/salamlang.ir/node_modules/next/dist/server/require-hook.js:65:28)
    at Object.<anonymous> (/var/www/html/salamlang.ir/node_modules/react-dom/server.browser.js:5:7) {
  type: 'TypeError'
}
error: script "build" exited with code 1
root@maxbasecode:/var/www/html/salamlang.ir# git pull
Already up to date.
root@maxbasecode:/var/www/html/salamlang.ir# bun --version
1.1.38
root@maxbasecode:/var/www/html/salamlang.ir# npm --version
9.2.0
root@maxbasecode:/var/www/html/salamlang.ir#
root@maxbasecode:/var/www/html/salamlang.ir#
root@maxbasecode:/var/www/html/salamlang.ir# ls
bunfig.toml  jsconfig.json    node_modules  postcss.config.mjs  README.md  tailwind.config.js
bun.lockb    next.config.mjs  package.json  public              src
root@maxbasecode:/var/www/html/salamlang.ir#
```

**Comment by BaseMax** [comment]
```
root@maxbasecode:/var/www/html/salamlang.ir# node --version
v18.19.1
```

**Comment by BaseMax** [comment]
سایت امد بالا.

**Comment by ali-josheghani** [comment]
خب اینو میبندم سایت بالاس
